# Generated by Django 5.1.5 on 2025-02-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='books',
            index=models.Index(fields=['name'], name='books_name_trgm_idx'),
        ),
        migrations.AddIndex(
            model_name='books',
            index=models.Index(fields=['isbn'], name='books_isbn_trgm_idx'),
        ),
        migrations.AddIndex(
            model_name='books',
            index=models.Index(fields=['author'], name='books_author_trgm_idx'),
        ),
        migrations.AddIndex(
            model_name='books',
            index=models.Index(fields=['pub'], name='books_pub_trgm_idx'),
        ),
    ]
