# Generated by Django 5.1.4 on 2024-12-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=100)),
                ('pub', models.CharField(max_length=150)),
                ('isbn', models.CharField(max_length=20)),
                ('copies_total', models.IntegerField()),
                ('copies_available', models.IntegerField()),
            ],
        ),
    ]
