# Generated by Django 5.1.4 on 2024-12-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_is_admin_profile_is_librarian'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='cover_img',
            field=models.ImageField(default='default.jpg', upload_to='cover_image'),
        ),
    ]
