# Generated by Django 5.1.4 on 2024-12-25 16:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='date_return',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
