# Generated by Django 5.1.4 on 2024-12-25 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_inventory_date_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.books'),
        ),
    ]
