# Generated by Django 5.1.4 on 2024-12-25 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_inventory_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='inventory',
        ),
    ]
