# Generated by Django 5.1.4 on 2024-12-25 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_inventory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='inventory',
        ),
    ]
