# Generated by Django 5.1.4 on 2024-12-26 07:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_borrowbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowbook',
            name='date_borrow',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 26, 7, 6, 1, 830358, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='borrowbook',
            name='date_return',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 26, 7, 6, 1, 830383, tzinfo=datetime.timezone.utc)),
        ),
    ]
