# Generated by Django 5.1.4 on 2024-12-26 07:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_borrowbook_date_borrow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowbook',
            name='date_borrow',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='borrowbook',
            name='date_return',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
