# Generated by Django 5.1.4 on 2024-12-26 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_library_settings_returnbook_is_latefees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowbook',
            name='book',
        ),
        migrations.RemoveField(
            model_name='borrowbook',
            name='user',
        ),
        migrations.DeleteModel(
            name='library_settings',
        ),
        migrations.RemoveField(
            model_name='returnbook',
            name='book',
        ),
        migrations.RemoveField(
            model_name='returnbook',
            name='user',
        ),
        migrations.DeleteModel(
            name='borrowBook',
        ),
        migrations.DeleteModel(
            name='returnBook',
        ),
    ]
