# Generated by Django 5.1.4 on 2024-12-26 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_borrowbook_returnbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnbook',
            name='book',
        ),
        migrations.RemoveField(
            model_name='returnbook',
            name='user',
        ),
        migrations.DeleteModel(
            name='borrowBook',
        ),
        migrations.DeleteModel(
            name='returnBook',
        ),
    ]
