# Generated by Django 5.1.4 on 2024-12-26 23:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_borrowbook_returnbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnbook',
            name='date_borrow',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='returnbook',
            name='date_return',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
