# Generated by Django 5.1.4 on 2024-12-27 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_feedback_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='title',
            new_name='subject',
        ),
    ]
