# Generated by Django 5.1.4 on 2024-12-29 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_placeholder.jpg', upload_to='profile_pics'),
        ),
    ]
