# Generated by Django 5.1.4 on 2024-12-29 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_profile_hostel_profile_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hostel',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='room',
            field=models.CharField(default=None, max_length=4, null=True),
        ),
    ]
