# Generated by Django 5.1.4 on 2024-12-29 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_remove_profile_hostel_remove_profile_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hostel',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='room',
            field=models.CharField(blank=True, default=None, max_length=4, null=True),
        ),
    ]
