# Generated by Django 5.1.4 on 2024-12-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_profile_hostel_profile_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_placeholder.jpg', upload_to='profile_pics'),
        ),
    ]
