# Generated by Django 5.1.4 on 2024-12-29 08:56

from django.db import migrations, models

def update_default_image(apps, schema_editor):
    Profile = apps.get_model('home', 'Profile')
    new_url = 'profile_pics/default.jpg'  # Replace with your old default URL
    old_url = 'default.jpg'  # Replace with your new default URL

    Profile.objects.filter(image=old_url).update(image=new_url)


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_auto_20241229_0804'),
    ]

    operations = [
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics'),
        ),
    ]