# Generated by Django 5.1.4 on 2024-12-29 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='img',
        ),
    ]
