# Generated by Django 5.1.4 on 2025-01-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_library_settings_compound_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnbook',
            name='lateFees_final',
            field=models.IntegerField(default=0),
        ),
    ]
