# Generated by Django 5.1.4 on 2025-01-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_returnbook_latefees_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnbook',
            name='lateFees_final',
            field=models.FloatField(default=0),
        ),
    ]
