# Generated by Django 5.1.4 on 2025-01-22 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_alter_returnbook_latefees_final'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='cover_img',
        ),
    ]
